# -*- coding: utf-8 -*-
# Расширяет описания всех вин (поле d) в wine.js (RU) и wine_en.js (EN)
# до 1-2 предложений. Названия (n) и структура не меняются.
import re, sys

# slug -> список [ru, en] по порядку вин в регионе (как в wine.js / wine_en.js)
DESC = {
 "w-bordeaux": [
  ["Первый гран-крю Медока по классификации 1855 года: шелковистые танины, аромат фиалки и кедра. Одно из самых элегантных и долгоживущих вин Бордо.",
   "A first growth of the Medoc in the 1855 classification: silky tannins with violet and cedar. One of Bordeaux's most elegant and age-worthy wines."],
  ["Эталон каберне-совиньона из Пойяка с нотами кедра, графита и чёрной смородины. Способно достойно стареть более ста лет и считается вершиной коллекционных вин.",
   "The Cabernet Sauvignon benchmark from Pauillac, with cedar, graphite and blackcurrant. It can age gracefully for over a century and is a pinnacle of collectible wine."],
  ["Культовое мерло с участка голубой глины в Помроле — плотное, бархатистое, с нотами трюфеля. Одно из самых редких и дорогих вин мира.",
   "Cult Merlot from the blue-clay plot of Pomerol, dense and velvety with truffle notes. One of the rarest and most expensive wines in the world."],
  ["Легендарное сладкое вино из семильона, поражённого благородной плесенью ботритис. Тягучее, с ароматами абрикоса, мёда и засахаренной цедры, живёт веками.",
   "The legendary sweet wine from Semillon affected by noble rot (botrytis). Unctuous, with apricot, honey and candied peel, it can live for centuries."],
  ["Премьер-гран-крю-классе 'А' из Сент-Эмильона — редкий бархатистый купаж каберне-фран и мерло. Сочетает мощь и аромат фиалки с шелковистой текстурой.",
   "A Premier Grand Cru Classe 'A' of Saint-Emilion, a rare velvety blend of Cabernet Franc and Merlot. It marries power and violet perfume with a silky texture."],
 ],
 "w-burgundy": [
  ["Самое знаменитое и дорогое красное вино планеты — гран-крю пино-нуар с крошечного участка в Вон-Романе. Эфемерный многослойный аромат розы, специй и подлеска.",
   "The most famous and expensive red wine on earth, a grand cru Pinot Noir from a tiny plot in Vosne-Romanee. An ethereal, layered bouquet of rose, spice and forest floor."],
  ["Король белых бургундских вин: мощное, маслянистое шардоне гран-крю с минеральной глубиной. Способно развиваться в бутылке десятилетиями.",
   "The king of white Burgundy: a powerful, buttery grand cru Chardonnay with mineral depth. It can develop in bottle for decades."],
  ["Любимое вино Наполеона, 'король вин и вино королей' — мощный структурный пино-нуар из Жевре-Шамбертен с нотами вишни, лакрицы и кожи.",
   "Napoleon's favourite, 'the king of wines and the wine of kings' — a powerful, structured Pinot Noir from Gevrey-Chambertin, with cherry, liquorice and leather."],
  ["Белый гран-крю с холма, по легенде принадлежавшего Карлу Великому. Богатое шардоне с нотами лесного ореха, мёда и кремня.",
   "A white grand cru from the hill said to have belonged to Charlemagne. A rich Chardonnay with hazelnut, honey and flinty minerality."],
  ["Исторический гран-крю за каменной стеной, заложенный монахами-цистерцианцами в XII веке. Земляничный пино-нуар с танинной основой и землистыми тонами.",
   "A historic grand cru behind a stone wall, planted by Cistercian monks in the 12th century. A wild-strawberry Pinot Noir with a tannic frame and earthy tones."],
 ],
 "w-champagne": [
  ["Престижное винтажное кюве дома Moet & Chandon, названное в честь монаха, усовершенствовавшего шампанское. Тонкий перляж с нотами бриоши, цитруса и миндаля.",
   "The prestige vintage cuvee of Moet & Chandon, named after the monk who refined Champagne. A fine mousse with brioche, citrus and almond."],
  ["Богатый мультивинтаж, частично выдержанный в дубовых бочках, — сложный купаж более ста вин разных лет. Ноты сухофруктов, орехов и мёда.",
   "A rich multi-vintage partly aged in oak, a complex blend of over a hundred wines from different years, with dried fruit, nuts and honey."],
  ["Создано в 1876 году для российского императора Александра II — отсюда прозрачная бутылка с плоским дном. Точное, минеральное и элегантное шампанское.",
   "Created in 1876 for Tsar Alexander II of Russia, hence the clear, flat-bottomed bottle. A precise, mineral and elegant Champagne."],
  ["Мощное винтажное шампанское на основе пино-нуара, выдержанное в старых бочках. Любимая марка Джеймса Бонда, с нотами выпечки и спелого яблока.",
   "A powerful Pinot Noir-based vintage Champagne aged in old barrels. James Bond's favourite, with notes of pastry and ripe apple."],
  ["Редчайший блан-де-блан из одной деревни Ле-Мениль-сюр-Ожер, выпускается только в лучшие годы. Кристально чистое, долгоживущее шардоне.",
   "An extremely rare blanc de blancs from the single village of Le Mesnil-sur-Oger, made only in the finest years. A crystalline, long-lived Chardonnay."],
 ],
 "w-loire": [
  ["Эталонный совиньон-блан с кремнистых и известняковых почв верхней Луары. Хрустящий, минеральный, с нотами крыжовника и дымка.",
   "The benchmark Sauvignon Blanc from the flint and limestone soils of the upper Loire. Crisp and mineral, with gooseberry and a smoky edge."],
  ["'Дымный' совиньон с противоположного от Сансера берега Луары, с характерной кремнёвой нотой. Свежий, с цитрусом и белыми цветами.",
   "The 'smoky' Sauvignon from the opposite bank to Sancerre, with a signature flinty note. Fresh, with citrus and white flowers."],
  ["Шенен-блан во всех стилях — от сухого до игристого и сладкого. Аромат айвы, мёда и акации с хрустящей кислотностью и большим потенциалом выдержки.",
   "Chenin Blanc in every style, from dry to sparkling to sweet. Quince, honey and acacia, with crisp acidity and great ageing potential."],
  ["Ароматный каберне-фран, воспетый Рабле, уроженцем этих мест. Лёгкое красное с нотами малины, графита и болгарского перца.",
   "Aromatic Cabernet Franc, celebrated by Rabelais, a local son. A light red with raspberry, graphite and bell-pepper notes."],
  ["Строгий, долгоживущий сухой шенен-блан с южных сланцевых склонов Анжу. Минеральное восковое вино, раскрывающееся годами.",
   "A strict, long-lived dry Chenin Blanc from the schist slopes of Anjou. A mineral, waxy wine that unfolds over years."],
 ],
 "w-rhone": [
  ["Историческое вино летней резиденции пап под Авиньоном: купаж до 13 сортов во главе с гренашем на округлых камнях-галет. Тёплое, пряное, с нотами гарриги.",
   "The historic wine of the popes' summer residence near Avignon: a blend of up to 13 grapes led by Grenache on rounded galets pebbles. Warm and spicy, with garrigue herbs."],
  ["Мужественная сира с крутого гранитного холма над Роной — мощная, с нотами чёрных ягод, бекона и фиалки. Одно из самых долгоживущих красных Франции.",
   "A muscular Syrah from a steep granite hill above the Rhone, powerful with black fruit, bacon and violet. One of France's longest-lived reds."],
  ["'Жареный склон' — изящная сира с добавлением белого вионье, что придаёт аромат фиалки и абрикоса. Шелковистое северное вино Роны.",
   "The 'roasted slope' — an elegant Syrah co-fermented with white Viognier that adds violet and apricot. A silky northern-Rhone red."],
  ["Ароматное белое из вионье — единственного сорта апелласьона. Пышное, с нотами персика, абрикоса и жимолости, лучше пить молодым.",
   "An aromatic white from Viognier, the sole grape of the appellation. Opulent, with peach, apricot and honeysuckle; best drunk young."],
  ["Сосед Шатонёф-дю-Пап на склонах Дантель-де-Монмирай: насыщенное гренаш-вино с пряностью и нотами вишни и гарриги.",
   "A neighbour of Chateauneuf on the slopes of the Dentelles de Montmirail: a rich Grenache-based wine, spicy with cherry and garrigue."],
 ],
 "w-alsace": [
  ["Сухой, кристально чистый рислинг с гран-крю склонов Эльзаса. Минеральный, с нотами лайма, керосина и белых цветов, с возрастом усложняется.",
   "A dry, crystalline Riesling from Alsace's grand cru slopes. Mineral, with lime, petrol and white flowers, gaining complexity with age."],
  ["Душистый сорт с интенсивным ароматом розы, личи и пряностей. Полнотелое, чуть маслянистое вино, классическая пара к фуа-гра.",
   "A perfumed grape with intense rose, lychee and spice. A full-bodied, slightly oily wine, the classic match for foie gras."],
  ["Эльзасский пино-гри — плотное, дымчатое белое с нотами груши, мёда и грибов. Бывает сухим и сладким, отлично сочетается с белым мясом.",
   "Alsace Pinot Gris, a dense, smoky white with pear, honey and mushroom. Made dry or sweet, excellent with white meats."],
  ["Сухой мускат с поразительно виноградным ароматом свежесорванной грозди. Лёгкое, ароматное вино для аперитива.",
   "A dry Muscat with a strikingly grapey aroma of freshly picked fruit. A light, fragrant aperitif wine."],
  ["Игристое по классической технологии из пино-блана и других сортов. Свежее, с тонким перляжем — доступная альтернатива шампанскому.",
   "A traditional-method sparkler from Pinot Blanc and other grapes. Fresh, with a fine mousse, an affordable alternative to Champagne."],
 ],
 "w-provence": [
  ["Бледно-розовое сухое вино — икона прованского лета. Нежные ноты клубники, персика и трав, идеально охлаждённым у моря.",
   "A pale, dry rose, the icon of a Provencal summer. Delicate strawberry, peach and herbs, perfect chilled by the sea."],
  ["Мощное красное из сорта мурведр с приморских террас Бандоля. Танинное, с нотами ежевики, кожи и гарриги, требует выдержки.",
   "A powerful red from Mourvedre on the seaside terraces of Bandol. Tannic, with blackberry, leather and garrigue; it needs ageing."],
  ["Свежее белое из маленького приморского апелласьона у Марселя (не путать с ликёром). Морское, с нотами фенхеля и цитруса, к буйабесу.",
   "A fresh white from the small coastal appellation near Marseille (not the liqueur). Saline, with fennel and citrus, made for bouillabaisse."],
  ["Крошечный исторический апелласьон под Экс-ан-Провансом. Красные, белые и розе с травянистой пряностью, известные с XVI века.",
   "A tiny historic appellation near Aix-en-Provence. Reds, whites and roses with herbal spice, renowned since the 16th century."],
  ["Самое продаваемое прованское розе в мире от Chateau d'Esclans. Лёгкое, элегантное, с ягодными и цветочными нотами.",
   "The world's best-selling Provence rose, from Chateau d'Esclans. Light and elegant, with berry and floral notes."],
 ],
 "w-languedoc": [
  ["Свежее красное с прохладных известняковых склонов под одноимённым пиком. Сира и гренаш с нотами гарриги, перца и тёмных ягод.",
   "A fresh red from the cool limestone slopes below the eponymous peak. Syrah and Grenache with garrigue, pepper and dark fruit."],
  ["Первый 'крю' Лангедока — концентрированное красное с каменистых террас. Тёплые ноты ежевики, тимьяна и какао.",
   "Languedoc's first 'cru', a concentrated red from stony terraces, with warm blackberry, thyme and cocoa."],
  ["Красное со сланцевых почв, придающих минеральность и пряность. Гренаш, сира и кариньян с нотами гарриги и тёмных фруктов.",
   "A red from schist soils that lend minerality and spice. Grenache, Syrah and Carignan with garrigue and dark fruit."],
  ["Креплёное сладкое вино из муската с побережья Руссильона. Ароматы апельсиновой цедры, мёда и винограда, к десертам.",
   "A fortified sweet Muscat from the Roussillon coast. Orange peel, honey and grape, a dessert wine."],
  ["Хрустящее белое из сорта пикпуль у лагуны Этан-де-То. Свежее, цитрусовое, классическая пара к устрицам.",
   "A crisp white from the Piquepoul grape by the Thau lagoon. Fresh and citrusy, the classic match for oysters."],
 ],
 "w-beaujolais": [
  ["Один из лучших крю Божоле из гамэ с участка Кот-дю-Пи. Глубокое вино с нотами вишни, которое с годами 'бургундится'.",
   "One of the top Beaujolais crus, Gamay from the Cote du Py. A deep, cherry-laced wine that grows 'Burgundian' with age."],
  ["'Цветочный' крю Божоле — самый изящный и ароматный гамэ. Ноты пиона, фиалки и красных ягод, шелковистая текстура.",
   "The 'floral' Beaujolais cru, the most elegant and perfumed Gamay, with peony, violet and red berries and a silky texture."],
  ["Самый мощный и структурный крю Божоле, названный по старой ветряной мельнице. Танинное гамэ с потенциалом выдержки.",
   "The most powerful, structured Beaujolais cru, named after an old windmill. A tannic Gamay with real ageing potential."],
  ["Самый крупный крю Божоле у подножия горы Бруйи. Сочное фруктовое гамэ с нотами сливы и свежего винограда.",
   "The largest Beaujolais cru at the foot of Mont Brouilly. A juicy, fruity Gamay with plum and fresh grape."],
  ["Молодое вино, выпускаемое в третий четверг ноября — праздник первого урожая. Лёгкое, фруктовое, с нотами банана и красных ягод.",
   "A young wine released on the third Thursday of November, a celebration of the new harvest. Light and fruity, with banana and red berries."],
 ],
 "w-jura": [
  ["'Жёлтое вино' из саваньена, выдержанное под плёнкой дрожжей шесть лет в неполной бочке. Ореховое, с нотами карри, в фирменной бутылке клавлен.",
   "The 'yellow wine' from Savagnin, aged six years under a yeast film in a partly filled barrel. Nutty, with curry notes, in its signature clavelin bottle."],
  ["Соломенное вино из подвяленного на соломе винограда. Густое, сладкое, с нотами абрикоса, изюма и мёда.",
   "A 'straw wine' from grapes dried on straw mats. Thick and sweet, with apricot, raisin and honey."],
  ["Местный белый сорт Юры: в окислительном стиле даёт ореховые тона, в свежем — цветочные. Основа знаменитого вин-жона.",
   "The Jura's signature white grape; oxidative styles give nutty notes, fresh ones floral. The base of the famous vin jaune."],
  ["Редкий красный сорт Юры — лёгкое ароматное вино с нотами красных ягод, специй и подлеска.",
   "A rare Jura red grape, a light and aromatic wine with red berries, spice and forest floor."],
  ["Игристое по классической технологии, в основном из шардоне и пино-нуара. Свежее, с тонкими нотами выпечки и яблока.",
   "A traditional-method sparkler, mainly Chardonnay and Pinot Noir. Fresh, with subtle pastry and apple."],
 ],
 "w-savoie": [
  ["Лёгкое альпийское белое из сорта жакер. Свежее, минеральное, с нотами зелёного яблока и горных трав, к сырному фондю.",
   "A light Alpine white from the Jacquere grape. Fresh and mineral, with green apple and mountain herbs, made for cheese fondue."],
  ["Более плотное белое из сорта алтес (руссет). Ноты лесного ореха, груши и мёда, с приятной текстурой.",
   "A fuller white from the Altesse (Roussette) grape, with hazelnut, pear and honey and a pleasing texture."],
  ["Савойское белое из руссана (бержерон). Ароматное, с нотами абрикоса, мёда и специй, с округлым телом.",
   "A Savoie white from Roussanne (Bergeron). Aromatic, with apricot, honey and spice and a rounded body."],
  ["Местный красный сорт Савойи — пряное тёмное вино с нотами чёрного перца, ежевики и фиалки.",
   "Savoie's native red grape, a spicy dark wine with black pepper, blackberry and violet."],
  ["Лёгкое белое из шасла с берегов Женевского озера. Тонкое, минеральное, с нотами цитруса и кремня.",
   "A light Chasselas white from the shores of Lake Geneva. Delicate and mineral, with citrus and flint."],
 ],
 "w-cahors": [
  ["Родина мальбека — тёмное, почти чёрное вино, исторически 'чёрное вино' Кагора. Мощные танины, ноты сливы, какао и фиалки.",
   "The homeland of Malbec, a dark, almost black wine, historically the 'black wine' of Cahors. Powerful tannins with plum, cocoa and violet."],
  ["Суровое танинное красное из сорта танна с юго-запада Франции. Требует выдержки, раскрывая ноты чёрной смородины и специй.",
   "A sternly tannic red from the Tannat grape of south-west France. It needs ageing to reveal blackcurrant and spice."],
  ["Ароматное белое из предгорий Пиренеев, бывает сухим и сладким. Ноты экзотических фруктов и мёда; им крестили Генриха IV.",
   "An aromatic white from the Pyrenean foothills, made dry or sweet, with exotic fruit and honey; Henry IV was baptised with it."],
  ["Один из старейших винодельческих районов Франции с редкими местными сортами. Разнообразные стили — от игристого до сладкого.",
   "One of France's oldest wine areas, with rare local grapes and a range of styles from sparkling to sweet."],
  ["Бордоский по духу купаж мерло и каберне с юго-запада. Доступное, мягкое красное с нотами тёмных ягод.",
   "A Bordeaux-style blend of Merlot and Cabernet from the south-west. An approachable, supple red with dark fruit."],
 ],
 "w-corsica": [
  ["Первый апелласьон Корсики на известняках севера острова. Красные из ньеллуччо (сангиовезе) и ароматные белые из верментино.",
   "Corsica's first appellation, on the limestone of the island's north. Reds from Niellucciu (Sangiovese) and aromatic Vermentino whites."],
  ["Апелласьон вокруг родного города Наполеона из местного сорта сьяккарелло. Пряное, изящное красное с горными травами.",
   "The appellation around Napoleon's birthplace, from the local Sciaccarellu grape. A spicy, elegant red with mountain herbs."],
  ["Креплёное сладкое из муската с северного мыса острова. Ароматы цветов апельсина, мёда и винограда.",
   "A fortified sweet Muscat from the island's northern cape, with orange blossom, honey and grape."],
  ["Один из самых южных и древних винных районов Корсики с ветреным сухим климатом. Концентрированные красные и белые.",
   "One of Corsica's southernmost and oldest wine areas, windy and dry, giving concentrated reds and whites."],
  ["Корсиканское имя верментино — свежее белое с нотами груши, миндаля и морского бриза, к рыбе и морепродуктам.",
   "The Corsican name for Vermentino, a fresh white with pear, almond and sea breeze, for fish and seafood."],
 ],
 "w-tuscany": [
  ["Великое тосканское красное из 100% санджовезе, выдержанное минимум пять лет. Мощное, с нотами вишни, кожи и табака, живёт десятилетиями.",
   "A great Tuscan red from 100% Sangiovese, aged at least five years. Powerful, with cherry, leather and tobacco; it lives for decades."],
  ["Классическое тосканское вино с петухом 'Галло Неро' на горлышке. Санджовезе с нотами вишни, фиалки и трав, гастрономичное и живое.",
   "The classic Tuscan wine with the Gallo Nero (black rooster) seal. Sangiovese with cherry, violet and herbs, lively and food-friendly."],
  ["Первое 'супертосканское' вино из каберне на побережье Болгери, изменившее историю итальянского виноделия. Элегантное, бордоского стиля.",
   "The first 'Super Tuscan', a Cabernet from the Bolgheri coast that changed Italian wine history. Elegant and Bordeaux-like."],
  ["Знаменитое супертосканское от Antinori — купаж санджовезе с каберне, выдержанный в барриках. Гладкое, пряное, международного класса.",
   "The famous Super Tuscan from Antinori, Sangiovese blended with Cabernet and aged in barriques. Smooth, spicy and world-class."],
  ["'Благородное вино' из санджовезе (здесь — пруньоло джентиле) города Монтепульчано. Элегантное, с нотами вишни и специй.",
   "The 'noble wine' from Sangiovese (here called Prugnolo Gentile) of Montepulciano. Elegant, with cherry and spice."],
 ],
 "w-piedmont": [
  ["'Король вин и вино королей' из сорта неббиоло в Пьемонте. Мощное, танинное, с нотами розы, дёгтя и вишни, требует долгой выдержки.",
   "The 'king of wines and wine of kings', from Nebbiolo in Piedmont. Powerful and tannic, with rose, tar and cherry; it demands long ageing."],
  ["Более изящный брат Бароло из того же неббиоло. Ароматный, с нотами розы, малины и специй, мягче в молодости.",
   "The more graceful sibling of Barolo, from the same Nebbiolo. Perfumed, with rose, raspberry and spice, softer when young."],
  ["Сочное повседневное красное из сорта барбера с яркой кислотностью и низкими танинами. Ноты вишни и сливы.",
   "A juicy everyday red from the Barbera grape, with bright acidity and low tannins. Cherry and plum."],
  ["Лёгкое сладкое слабоигристое из муската с низким алкоголем. Ароматы персика, цветов и винограда, к десертам.",
   "A light, sweet, lightly sparkling Moscato, low in alcohol, with peach, blossom and grape, a dessert wine."],
  ["Свежее сухое белое из сорта кортезе. Минеральное, цитрусовое, с нотами зелёного яблока, к морепродуктам.",
   "A fresh dry white from the Cortese grape. Mineral and citrusy, with green apple, for seafood."],
 ],
 "w-veneto": [
  ["Мощное сухое красное из подвяленного винограда (аппассименто). Концентрированное, с нотами вишни в шоколаде, изюма и специй, высокий алкоголь.",
   "A powerful dry red from dried grapes (appassimento). Concentrated, with chocolate-cherry, raisin and spice and high alcohol."],
  ["Лучшее просекко с холмов Конельяно-Вальдоббьядене из сорта глера. Лёгкое, с нотами груши, яблока и белых цветов.",
   "The finest Prosecco from the Conegliano-Valdobbiadene hills, from the Glera grape. Light, with pear, apple and white flowers."],
  ["Классическое белое из сорта гарганега у Вероны. Минеральное, с нотами миндаля, груши и белых цветов.",
   "A classic white from the Garganega grape near Verona. Mineral, with almond, pear and white flowers."],
  ["'Малый амароне' — Вальполичелла, повторно настоянная на выжимках амароне. Глубже и насыщеннее обычной, с нотами вишни и специй.",
   "The 'baby Amarone', a Valpolicella re-passed over the Amarone skins. Deeper and richer than the standard, with cherry and spice."],
  ["Сладкий предок амароне из подвяленного винограда. Бархатистое десертное красное с нотами вишни и шоколада.",
   "The sweet ancestor of Amarone, from dried grapes. A velvety dessert red with cherry and chocolate."],
 ],
 "w-sicily": [
  ["Элегантное вулканическое красное из нерелло маскалезе со склонов Этны. Минеральное, с нотами вишни, дыма и трав, в бургундском стиле.",
   "An elegant volcanic red from Nerello Mascalese on the slopes of Etna. Mineral, with cherry, smoke and herbs, in a Burgundian style."],
  ["Главный красный сорт Сицилии — насыщенное тёплое вино с нотами сливы, чёрной вишни и специй.",
   "Sicily's flagship red grape, a rich and warm wine with plum, black cherry and spice."],
  ["Сладкое вино из подвяленного муската зибиббо с ветреного острова Пантеллерия. Ароматы абрикоса, мёда и инжира.",
   "A sweet wine from dried Zibibbo Muscat on the windy island of Pantelleria. Apricot, honey and fig."],
  ["Историческое креплёное вино западной Сицилии, от сухого к сладкому. Ноты карамели, ореха и сухофруктов, для аперитива и кулинарии.",
   "The historic fortified wine of western Sicily, dry to sweet. Caramel, nut and dried fruit, for sipping and cooking."],
  ["Единственное DOCG Сицилии — купаж неро-д'авола и фраппато. Свежее, вишнёвое, с цветочным ароматом.",
   "Sicily's only DOCG, a blend of Nero d'Avola and Frappato. Fresh and cherry-driven, with a floral lift."],
 ],
 "w-rioja": [
  ["Вершина Риохи из темпранильо, выдержанная годами в дубе и бутылке. Шелковистое, с нотами кожи, ванили, сухофруктов и табака.",
   "The summit of Rioja, Tempranillo aged for years in oak and bottle. Silky, with leather, vanilla, dried fruit and tobacco."],
  ["Легендарное вино Lopez de Heredia в старинном окислительном стиле, с очень долгой выдержкой. Сложное, с нотами вяленых фруктов и специй.",
   "The legendary Lopez de Heredia wine in an old oxidative style, with very long ageing. Complex, with dried fruit and spice."],
  ["Один из старейших и самых известных домов Риохи (с 1858 года). Классическое темпранильо с нотами вишни, ванили и кожи.",
   "One of Rioja's oldest and most famous houses (since 1858). A classic Tempranillo with cherry, vanilla and leather."],
  ["Историческая марка дома CVNE из Аро; её Gran Reserva признавалось лучшим вином мира. Элегантное, традиционное темпранильо.",
   "A historic label from the CVNE house in Haro; its Gran Reserva was once named the world's best wine. Elegant, traditional Tempranillo."],
  ["Белая Риоха из виуры, бывает свежей и дубовой. Выдержанные версии маслянистые, с нотами ореха и ванили.",
   "White Rioja from Viura, made fresh or oaked. Aged versions are buttery, with nut and vanilla."],
 ],
 "w-ribera": [
  ["Самое престижное вино Испании из Рибера-дель-Дуэро, выдержанное десять и более лет. Темпранильо с каберне, невероятно сложное и долгоживущее.",
   "Spain's most prestigious wine, from Ribera del Duero, aged ten years or more. Tempranillo with Cabernet, extraordinarily complex and long-lived."],
  ["Культовое гаражное вино со старых лоз темпранильо, одно из самых редких в Испании. Плотное, бархатистое, концентрированное.",
   "A cult 'garage' wine from old Tempranillo vines, one of Spain's rarest. Dense, velvety and concentrated."],
  ["Вино Алехандро Фернандеса, прославившее регион. Мощное темпранильо ('тинто фино') с нотами тёмных ягод и дуба.",
   "Alejandro Fernandez's wine that put the region on the map. A powerful Tempranillo (Tinto Fino) with dark fruit and oak."],
  ["Современное вино от бывшего винодела Vega Sicilia. Концентрированное темпранильо со старых лоз, гладкое и пряное.",
   "A modern wine from a former Vega Sicilia winemaker. Concentrated old-vine Tempranillo, smooth and spicy."],
  ["Семейное темпранильо со старых лоз, образец стиля Рибера-дель-Дуэро. Сочное, с нотами чёрных ягод и специй.",
   "A family old-vine Tempranillo, a benchmark of Ribera del Duero style. Juicy, with black fruit and spice."],
 ],
 "w-jerez": [
  ["Сухой светлый херес, выдержанный под плёнкой дрожжей 'флор'. Солоноватый, с нотами миндаля и теста, подаётся охлаждённым.",
   "A dry, pale sherry aged under a film of 'flor' yeast. Saline, with almond and dough, served chilled."],
  ["Фино из приморского Санлукар-де-Баррамеда с особой солоноватой, морской нотой. Лёгкий и свежий аперитив.",
   "A Fino from coastal Sanlucar de Barrameda with a distinctive saline, sea-breeze note. A light, fresh aperitif."],
  ["Херес, начавший жизнь под флором, а затем окислявшийся. Янтарный, ореховый, с нотами лесного ореха и сухофруктов.",
   "A sherry that begins under flor, then ages oxidatively. Amber and nutty, with hazelnut and dried fruit."],
  ["Полнотелый окислительный херес без флора. Насыщенный, с нотами грецкого ореха, кожи и карамели, бывает сухим и сладким.",
   "A full-bodied oxidative sherry made without flor. Rich, with walnut, leather and caramel, dry or sweetened."],
  ["Густой сладкий херес из подвяленного на солнце винограда. Чёрный, как патока, с нотами изюма, инжира и кофе, к мороженому.",
   "A thick, sweet sherry from sun-dried grapes. Black as treacle, with raisin, fig and coffee, pour it over ice cream."],
 ],
 "w-douro": [
  ["Лучший портвейн одного выдающегося года, дображивающий в бутылке десятилетиями. Мощный, сладкий, с нотами чёрных ягод и специй.",
   "The finest Port of a single declared year, maturing in bottle for decades. Powerful and sweet, with black fruit and spice."],
  ["Портвейн долгой выдержки в бочке, янтарного цвета. Ноты карамели, ореха, инжира и сухофруктов, подаётся чуть охлаждённым.",
   "A barrel-aged Port of amber colour, with caramel, nut, fig and dried fruit, served lightly chilled."],
  ["Портвейн одного года, выдержанный в бочке 4-6 лет — доступная альтернатива винтажному. Насыщенный, с нотами сливы и шоколада.",
   "A single-year Port aged 4-6 years in cask, an affordable alternative to Vintage. Rich, with plum and chocolate."],
  ["Легендарный портвейн с крошечного участка непривитых лоз. Один из самых редких и дорогих в мире, исключительной концентрации.",
   "A legendary Port from a tiny plot of ungrafted vines. One of the world's rarest and most expensive, of exceptional concentration."],
  ["Сухое красное из тех же сортов, что и портвейн (тоурига насьональ и др.). Мощное, с нотами тёмных ягод, трав и минералов.",
   "A dry red from the same grapes as Port (Touriga Nacional and others). Powerful, with dark fruit, herbs and minerals."],
 ],
 "w-vinho": [
  ["Лучшее 'зелёное вино' из сорта альваринью на севере у реки Миньо. Ароматное, с нотами персика, цитруса и минералов.",
   "The finest Vinho Verde from Alvarinho in the north by the Minho river. Aromatic, with peach, citrus and minerals."],
  ["Цветочный сорт винью верде с нотами лавра, акации и лайма. Лёгкое, свежее, чуть игристое вино.",
   "A floral Vinho Verde grape with bay leaf, acacia and lime. A light, fresh, faintly spritzy wine."],
  ["Молодое 'зелёное вино' северной Португалии с лёгкой игристостью. Низкий алкоголь, хрустящая кислотность, к морепродуктам.",
   "A young 'green wine' of northern Portugal with a slight spritz. Low in alcohol and crisp, for seafood."],
  ["Свежее розе винью верде из сорта эшпадейру. Лёгкое, с нотами красных ягод и яркой кислотностью.",
   "A fresh Vinho Verde rose from the Espadeiro grape. Light, with red berries and bright acidity."],
  ["Сорт, придающий винью верде тело и ноты яблока и груши, часто в купажах. Мягче и округлее альваринью.",
   "A grape that lends Vinho Verde body with apple and pear, often in blends. Softer and rounder than Alvarinho."],
 ],
 "w-mosel": [
  ["Рислинг с одного из самых знаменитых и дорогих виноградников Мозеля. Тонкий, с нотами персика, сланца и цитруса.",
   "Riesling from one of the Mosel's most famous and expensive vineyards. Delicate, with peach, slate and citrus."],
  ["Легендарный рислинг от Egon Muller с Саара — одно из величайших белых вин мира. Эфемерное, минеральное, бессмертно долгоживущее.",
   "A legendary Riesling from Egon Muller on the Saar, one of the world's greatest whites. Ethereal, mineral and immortally long-lived."],
  ["Рислинг с крутого сланцевого склона с солнечными часами. Чуть сладкий, с нотами персика, мёда и кремня.",
   "Riesling from the steep slate slope with its sundial. Off-dry, with peach, honey and flint."],
  ["Лёгкий, изящный рислинг с низким алкоголем — повседневная классика Мозеля. Свежий, с нотами яблока, лайма и сланца.",
   "A light, delicate, low-alcohol Riesling, the Mosel's everyday classic. Fresh, with apple, lime and slate."],
  ["Ледяное вино из винограда, собранного и отжатого замёрзшим. Концентрированное, сладкое, с яркой кислотностью и нотами цитруса.",
   "An ice wine from grapes harvested and pressed while frozen. Concentrated and sweet, with vivid acidity and citrus."],
 ],
 "w-rheingau": [
  ["Историческое поместье, где, по легенде, открыли позднеспелый сбор (шпетлезе). Благородный сухой и сладкий рислинг с нотами персика и мёда.",
   "The historic estate where late harvest (Spatlese) was reportedly discovered. Noble dry and sweet Riesling with peach and honey."],
  ["Рислинг с крутейшего сланцевого склона над Рейном. Мощный, минеральный, с нотами абрикоса и дыма.",
   "Riesling from the steep slate slope above the Rhine. Powerful and mineral, with apricot and smoke."],
  ["Рислинг с обнесённого стеной монастырского виноградника, основанного цистерцианцами. Здесь снимали 'Имя розы'.",
   "Riesling from a walled monastic vineyard founded by Cistercians; 'The Name of the Rose' was filmed here."],
  ["Один из лучших немецких пино-нуаров (шпетбургундер) с красного сланца. Изящное красное с нотами вишни и специй.",
   "One of Germany's finest Pinot Noirs (Spatburgunder), from red slate. An elegant red with cherry and spice."],
  ["Редчайшее сладкое вино из заизюмленных ботритизированных ягод, собранных по одной. Густое, медовое, бессмертно долгоживущее.",
   "An extremely rare sweet wine from shrivelled, botrytised berries picked one by one. Thick, honeyed and immortally long-lived."],
 ],
 "w-tokaj": [
  ["Венгерское 'вино королей и король вин' из ботритизированных ягод. Золотистое, сладкое, с нотами абрикоса, мёда и цедры и яркой кислотностью.",
   "The Hungarian 'wine of kings and king of wines' from botrytised berries. Golden and sweet, with apricot, honey and peel and bright acidity."],
  ["Легендарный нектар из сока, вытекающего из ягод под собственным весом, с огромной сахаристостью. Одно из редчайших вин мира.",
   "A legendary nectar from juice that flows from the berries under their own weight, of immense sweetness. One of the rarest wines on earth."],
  ["Токай 'как уродилось' — из целых гроздей, бывает сухим и сладким. Окислительный стиль с ореховыми нотами.",
   "Tokaji made 'as it comes' from whole bunches, dry or sweet. An oxidative style with nutty notes."],
  ["Сухой фурминт — современное лицо Токая. Минеральное, мощное белое с нотами груши, цитруса и дыма.",
   "Dry Furmint, the modern face of Tokaj. A mineral, powerful white with pear, citrus and smoke."],
  ["'Липовый лист' — ароматный сорт Токая с нотами липы, мёда и пряностей, часто в купаже с фурминтом.",
   "'Linden leaf', an aromatic Tokaj grape with linden, honey and spice, often blended with Furmint."],
 ],
 "w-santorini": [
  ["Вулканическое белое из ассиртико со старых лоз, скрученных в корзины-'кулура' от ветра. Хрустящее, солёное, минеральное.",
   "A volcanic white from Assyrtiko on old vines trained into 'kouloura' baskets against the wind. Crisp, saline and mineral."],
  ["Традиционное насыщенное ассиртико, исторически собиравшееся ночью. Полнотелое, с нотами цитруса, мёда и дуба.",
   "A traditional, richer Assyrtiko historically picked at night. Full-bodied, with citrus, honey and oak."],
  ["Сладкое вино Санторини из подвяленных на солнце ягод ассиртико. Янтарное, с нотами изюма, инжира, кофе и карамели.",
   "Santorini's sweet wine from sun-dried Assyrtiko grapes. Amber, with raisin, fig, coffee and caramel."],
  ["Редкий местный красный сорт, спасённый от исчезновения. Плотное вино с нотами тёмных ягод, специй и вулканической минеральности.",
   "A rare native red grape saved from extinction. A dense wine with dark fruit, spice and volcanic minerality."],
  ["Ароматный белый сорт Санторини, часто в купаже с ассиртико. Цветочное, с нотами цитруса и трав.",
   "An aromatic Santorini white grape, often blended with Assyrtiko. Floral, with citrus and herbs."],
 ],
 "w-kakheti": [
  ["Грузинское природно-полусладкое красное из саперави с Алазанской долины. Бархатистое, с нотами вишни и чёрной смородины.",
   "A Georgian naturally semi-sweet red from Saperavi in the Alazani valley. Velvety, with cherry and blackcurrant."],
  ["Сухое выдержанное красное из саперави — эталон грузинской классики. Танинное, с нотами тёмных ягод и специй.",
   "A dry aged red from Saperavi, the benchmark of Georgian classics. Tannic, with dark fruit and spice."],
  ["Сухое белое из ркацители и мцване, выдержанное в дубе. Свежее, с нотами цитруса, груши и трав.",
   "A dry white from Rkatsiteli and Mtsvane, oak-aged. Fresh, with citrus, pear and herbs."],
  ["Янтарное 'оранжевое' вино, выдержанное на мезге в зарытых глиняных квеври по древней технологии из списка ЮНЕСКО. Танинное, с нотами орехов и сухофруктов.",
   "An amber 'orange' wine fermented on skins in buried clay qvevri, a UNESCO-listed ancient method. Tannic, with nuts and dried fruit."],
  ["Знаменитое природно-полусладкое красное из сортов александроули и муджуретули с нотами малины — вино, которое приписывают вкусам Сталина.",
   "A famous naturally semi-sweet red from Aleksandrouli and Mujuretuli grapes, with raspberry notes, said to have been Stalin's favourite."],
 ],
 "w-napa": [
  ["Культовое каберне-совиньон из Напы, одно из самых редких и дорогих вин Америки. Концентрированное, бархатистое, с нотами чёрных ягод.",
   "A cult Napa Cabernet Sauvignon, one of America's rarest and most expensive wines. Concentrated and velvety, with black fruit."],
  ["Совместное детище Мондави и барона Ротшильда — бордоский купаж из Напы. Элегантное, структурное, с нотами кассиса и кедра.",
   "The joint venture of Mondavi and Baron Rothschild, a Bordeaux blend from Napa. Elegant and structured, with cassis and cedar."],
  ["Каберне, победившее Бордо на 'Парижском суде' 1976 года и прославившее Калифорнию. Элегантное, с нотами тёмных ягод и специй.",
   "The Cabernet that beat Bordeaux at the 1976 'Judgment of Paris' and made California famous. Elegant, with dark fruit and spice."],
  ["Богатое, щедрое каберне Напы в фруктовом стиле. Спелые ноты чёрной вишни, ванили и шоколада, бархатистая текстура.",
   "A rich, generous Napa Cabernet in a fruit-driven style. Ripe black cherry, vanilla and chocolate with a velvety texture."],
  ["Шардоне, победившее на 'Парижском суде' 1976 года среди белых. Минеральное, с нотами яблока, цитруса и кремня.",
   "The Chardonnay that won the white flight at the 1976 'Judgment of Paris'. Mineral, with apple, citrus and flint."],
 ],
 "w-sonoma": [
  ["Пино-нуар из прохладной туманной долины Рашен-Ривер. Сочное, с нотами вишни, колы и пряностей.",
   "Pinot Noir from the cool, foggy Russian River Valley. Juicy, with cherry, cola and spice."],
  ["Шардоне с прохладного побережья Сономы. Свежее, с нотами цитруса, яблока и минералов, более сдержанное, чем в Напе.",
   "Chardonnay from the cool Sonoma Coast. Fresh, with citrus, apple and minerals, more restrained than Napa."],
  ["Зинфандель со старых лоз Сономы — мощное пряное красное с нотами ежевики, перца и джема.",
   "Old-vine Zinfandel from Sonoma, a bold, spicy red with blackberry, pepper and jam."],
  ["Культовое шардоне Сономы в бургундском стиле. Богатое, маслянистое, с нотами лесного ореха, цитруса и кремня.",
   "A cult Burgundian-style Sonoma Chardonnay. Rich and buttery, with hazelnut, citrus and flint."],
  ["Легендарный производитель пино-нуар с культовым статусом и листом ожидания. Шелковистое, ароматное, с нотами красных ягод.",
   "A legendary Pinot Noir producer with cult status and a waiting list. Silky and perfumed, with red berries."],
 ],
 "w-willamette": [
  ["Орегонский проект знаменитого бургундского дома Drouhin. Изящный пино-нуар с нотами вишни, земли и специй.",
   "The Oregon project of the famous Burgundy house Drouhin. An elegant Pinot Noir with cherry, earth and spice."],
  ["Пионер орегонского пино-нуара, посадивший первые лозы в долине Уилламетт. Тонкое, сдержанное, бургундского духа.",
   "The pioneer of Oregon Pinot Noir, who planted the valley's first vines. Delicate and restrained, Burgundian in spirit."],
  ["Ароматный пино-нуар с добавлением гребней для структуры. Ноты красных ягод, цветов и специй.",
   "An aromatic Pinot Noir made with whole-cluster fermentation for structure. Red berries, flowers and spice."],
  ["Свежее прохладноклиматическое шардоне Орегона. Минеральное, с нотами цитруса, яблока и лёгкого дуба.",
   "A fresh cool-climate Oregon Chardonnay. Mineral, with citrus, apple and light oak."],
  ["Главный белый сорт Орегона — более плотный, чем итальянский пино-гриджо. Ноты груши, дыни и специй.",
   "Oregon's signature white, fuller than Italian Pinot Grigio, with pear, melon and spice."],
 ],
 "w-mendoza": [
  ["Флагманский высокогорный мальбек, прославивший Аргентину. Мощное, с нотами чёрной сливы, фиалки и специй.",
   "The flagship high-altitude Malbec that made Argentina famous. Powerful, with black plum, violet and spice."],
  ["'Андский Шеваль Блан' — элегантный купаж мальбека и каберне от Cheval Blanc. Утончённое, структурное вино.",
   "The 'Cheval Blanc of the Andes', an elegant Malbec-Cabernet blend from Cheval Blanc. Refined and structured."],
  ["Концентрированный мальбек со старых лоз высокогорного участка Альтамира. Глубокое, бархатистое, с нотами тёмных ягод.",
   "A concentrated old-vine Malbec from the high-altitude Altamira plot. Deep and velvety, with dark fruit."],
  ["Один из старейших семейных домов Мендосы. Сбалансированный мальбек с нотами сливы, фиалки и пряностей.",
   "One of Mendoza's oldest family houses. A balanced Malbec with plum, violet and spice."],
  ["Ароматный белый сорт Аргентины с интенсивным цветочным букетом. Ноты розы, жасмина и цитруса при сухом вкусе.",
   "Argentina's aromatic white grape with an intense floral bouquet. Rose, jasmine and citrus, yet dry on the palate."],
 ],
 "w-chile": [
  ["Премиальный бордоский купаж — совместный проект Concha y Toro и барона Ротшильда. Элегантное, с нотами кассиса, табака и кедра.",
   "A premium Bordeaux blend, a joint venture of Concha y Toro and Baron Rothschild. Elegant, with cassis, tobacco and cedar."],
  ["Икона чилийского каберне-совиньон из Пуэнте-Альто. Мощное, элегантное, с нотами чёрной смородины, графита и специй.",
   "An icon of Chilean Cabernet Sauvignon from Puente Alto. Powerful and elegant, with blackcurrant, graphite and spice."],
  ["Культовый купаж от Эдуардо Чедвика и Роберта Мондави, символ чилийского терруара. Гладкое, минеральное, выразительное.",
   "A cult blend by Eduardo Chadwick and Robert Mondavi, a symbol of Chilean terroir. Smooth, mineral and expressive."],
  ["Карменер — 'потерянный' бордоский сорт, ставший визитной карточкой Чили. Бархатистое красное с нотами сливы, специй и болгарского перца.",
   "Carmenere, the 'lost' Bordeaux grape that became Chile's signature. A velvety red with plum, spice and bell pepper."],
  ["'Погреб дьявола' — всемирно известное доступное чилийское вино с легендой о дьяволе, охранявшем подвал. Сочное и фруктовое.",
   "The 'Devil's Cellar', a world-famous, affordable Chilean wine with a legend of the devil guarding the cellar. Juicy and fruity."],
 ],
 "w-stellenbosch": [
  ["Эталон пинотажа — фирменного южноафриканского сорта (кросс пино-нуара и сенсо). Мощное, с нотами сливы, дыма и мокко.",
   "The benchmark Pinotage, South Africa's signature grape (a Pinot Noir x Cinsaut cross). Bold, with plum, smoke and mocha."],
  ["Классический бордоский купаж исторического поместья. Элегантное, с нотами кассиса, кедра и табака.",
   "A classic Bordeaux blend from a historic estate. Elegant, with cassis, cedar and tobacco."],
  ["Главное красное региона — структурное каберне-совиньон с нотами чёрной смородины, специй и табака.",
   "The region's flagship red, a structured Cabernet Sauvignon with blackcurrant, spice and tobacco."],
  ["Шенен-блан со старых лоз — гордость ЮАР (здесь его зовут 'стин'). Богатое, с нотами айвы, мёда и тропических фруктов.",
   "Old-vine Chenin Blanc, South Africa's pride (locally 'Steen'). Rich, with quince, honey and tropical fruit."],
  ["Возрождённое легендарное сладкое вино из муската, которым восхищались Наполеон и европейские дворы. Медовое, с нотами цитруса и абрикоса.",
   "The revived legendary sweet Muscat once adored by Napoleon and Europe's courts. Honeyed, with citrus and apricot."],
 ],
 "w-barossa": [
  ["Самое знаменитое вино Австралии — мощная шираз от Penfolds. Концентрированное, с нотами тёмных ягод, лакрицы и дуба, живёт десятилетиями.",
   "Australia's most famous wine, a powerful Penfolds Shiraz. Concentrated, with dark fruit, liquorice and oak; it ages for decades."],
  ["Шираз со старых лоз, посаженных в XIX веке — соперник Grange. Глубокое, элегантное, с нотами сливы, специй и земли.",
   "A Shiraz from 19th-century old vines, Grange's great rival. Deep and elegant, with plum, spice and earth."],
  ["Шираз с добавлением вионье в стиле Кот-Роти — мощное, но ароматное. Ноты чёрных ягод, фиалки и шоколада.",
   "A Shiraz co-fermented with Viognier in a Cote-Rotie style, powerful yet fragrant, with black fruit, violet and chocolate."],
  ["Гренаш со старейших в мире лоз Баросса. Сочное, пряное красное с нотами малины, сливы и белого перца.",
   "Grenache from some of the world's oldest vines in Barossa. Juicy and spicy, with raspberry, plum and white pepper."],
  ["Сухой рислинг с прохладных высот Иден-Вэлли. Хрустящий, с нотами лайма, цветов и минералов, прекрасно стареет.",
   "A dry Riesling from the cool heights of Eden Valley. Crisp, with lime, blossom and minerals; it ages beautifully."],
 ],
 "w-marlborough": [
  ["Вино, прославившее новозеландский совиньон-блан на весь мир. Яркое, с нотами маракуйи, крыжовника и свежескошенной травы.",
   "The wine that made New Zealand Sauvignon Blanc world-famous. Vivid, with passionfruit, gooseberry and freshly cut grass."],
  ["Проект основателя Cloudy Bay — более тонкий, текстурный совиньон. Ноты цитруса, косточковых фруктов и кремня.",
   "A project from Cloudy Bay's founding winemaker, a subtler, textured Sauvignon, with citrus, stone fruit and flint."],
  ["Выдержанный в бочке совиньон-блан бордоского стиля. Сложный, с нотами косточковых фруктов, дыма и трав.",
   "A barrel-fermented, Bordeaux-style Sauvignon Blanc. Complex, with stone fruit, smoke and herbs."],
  ["Лёгкий, ароматный пино-нуар прохладного климата с нотами вишни, сливы и трав.",
   "A light, aromatic cool-climate Pinot Noir with cherry, plum and herbs."],
  ["Игристое по классической технологии из шардоне и пино-нуара. Свежее, с нотами цитруса, яблока и выпечки.",
   "A traditional-method sparkling from Chardonnay and Pinot Noir. Fresh, with citrus, apple and pastry."],
 ],
 "w-crimea": [
  ["Легендарное десертное вино 'Массандры', многократный обладатель гран-при. Янтарное, с нотами розы, цитрона и мёда.",
   "The legendary Massandra dessert wine, a multiple Grand Prix winner. Amber, with rose, citron and honey."],
  ["Крымский херес окислительного стиля, выдержанный под солнцем. Ноты ореха, сухофруктов и солоноватый финиш.",
   "A Crimean oxidative-style sherry, sun-aged. Nutty, with dried fruit and a saline finish."],
  ["Историческая марка от основателя русского виноделия Льва Голицына. Изысканное десертное вино с богатым букетом.",
   "A historic label from Lev Golitsyn, the founder of Russian winemaking. A refined dessert wine with a rich bouquet."],
  ["Редкое десертное красное из автохтонного сорта эким-кара под Солнечной Долиной. Бархатистое, с нотами чернослива, шоколада и чёрных ягод.",
   "A rare dessert red from the native Ekim-Kara grape near Solnechnaya Dolina. Velvety, with prune, chocolate and black fruit."],
  ["Российское классическое игристое из Нового Света, основанного князем Голицыным. Свежее, с тонким перляжем и нотами яблока и выпечки.",
   "Russian traditional-method sparkling from Novy Svet, founded by Prince Golitsyn. Fresh, with a fine mousse, apple and pastry."],
 ],
}

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

WINE = re.compile(r'(\{\s*n:\s*"(?:[^"\\]|\\.)*"\s*,\s*d:\s*")((?:[^"\\]|\\.)*)("\s*\})')

def patch(path, region_re, lang_idx):
    text = open(path, encoding='utf-8').read()
    pieces = []
    last = 0
    total = 0
    seen = set()
    for m in re.finditer(region_re, text, re.S):
        slug = m.group(1)
        if slug not in DESC:
            raise SystemExit("No DESC for region " + slug)
        seen.add(slug)
        block = m.group(0)
        descs = DESC[slug]
        cnt = [0]
        def rep(wm):
            i = cnt[0]
            cnt[0] += 1
            d = descs[i][lang_idx]
            return wm.group(1) + esc(d) + wm.group(3)
        newblock = WINE.sub(rep, block)
        if cnt[0] != len(descs):
            raise SystemExit("%s: expected %d wines, replaced %d" % (slug, len(descs), cnt[0]))
        pieces.append(text[last:m.start()])
        pieces.append(newblock)
        last = m.end()
        total += cnt[0]
    pieces.append(text[last:])
    missing = set(DESC) - seen
    if missing:
        raise SystemExit("Regions not found in %s: %s" % (path, missing))
    open(path, 'w', encoding='utf-8').write(''.join(pieces))
    return total

ru = patch('js/data/wine.js', r'\{img:"(w-[^"]+)",.*?wines:\s*\[.*?\]\s*\}', 0)
en = patch('js/data/wine_en.js', r'"(w-[^"]+)":\s*\{.*?wines:\s*\[.*?\]\s*\}', 1)
print("RU descriptions replaced:", ru)
print("EN descriptions replaced:", en)
